import type { IFeedItem } from "@/types";

export const articles: IFeedItem[] = [
  {
    id: "fhi35568ub9484",
    alt: "",
    imgSrc: "/assets/images/spotlight4.webp",
    width: 1422,
    height: 798,
    category: { name: "World News", href: "/" },
    title:
      "Hong Kong Protester Dragged Into Chinese Consulate in UK and Beaten Up",
    description: "“They feel they can get away with it.”",
    author: "RACHEL CHEUNG",
    articleLink: "/",
    releaseDate: "10.06.22",
    isTrending: true,
    slug: "Hong-Kong-Protester-Dragged-Into-Chinese-Consulate",
  },
  {
    id: "fhi357wucxsbw484",
    alt: "",
    imgSrc: "/assets/images/girl.webp",
    width: 884,
    height: 496,
    category: { name: "World News", href: "/" },
    title:
      "She Died After Taking MDMA. Her Friends Burned Her Body to Escape Drug Charges.",
    description:
      "How and why 19-year-old Felicia Teo vanished remained a mystery until last week, when a Singaporean court finally heard what happened that night.",
    author: "KOH EWE",
    articleLink: "/",
    releaseDate: "10.06.22",
    slug: "She-Died-After-Taking-MDMA",
  },
  {
    id: "fhw4365nmubaw484",
    alt: "",
    imgSrc: "/assets/images/wc.webp",
    width: 884,
    height: 496,
    category: { name: "Science", href: "/" },
    title: "We Asked an Expert Why Vaping Makes You Want To Poo",
    description:
      "“If you were to stop vaping, or consuming nicotine, you would probably become constipated. Probably, for a couple of days.”",
    author: "JULIE FENWICK",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "We-Asked-an-Expert-Why-Vaping-Makes-You-Want-To-Poo",
  },
  {
    id: "fhiwehesashw484",
    alt: "",
    imgSrc: "/assets/images/coffeecup.webp",
    width: 884,
    height: 496,
    category: { name: "events", href: "/" },
    title: "VICE AUSTRALIA GUIDE TO THE WEEKEND",
    description:
      "Here’s what to do this weekend in and around the world (Australia) ✰ OCTOBER WEEK 2 ✰",
    author: "ARIELLE RICHARDS",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "what-to-do-this-weekend",
  },
  {
    id: "fhiwehesghw484",
    alt: "",
    imgSrc: "/assets/images/girl2.webp",
    width: 884,
    height: 496,
    category: { name: "life", href: "/" },
    title:
      "The Teen Magazine Raised an Entire Generation of Girls. Where Is It Now?",
    description:
      "Nostalgic posts on social media show that there’s a longing for the unique guidance and glamour that teen magazines provided in their heyday.",
    author: "ARIELLE RICHARDS",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "The-Teen-Magazine-Raised-an-Entire-Generation-of-Girls",
  },
  {
    id: "fhiwehesfhw484",
    alt: "",
    imgSrc: "/assets/images/girl3.webp",
    width: 884,
    height: 496,
    category: { name: "life", href: "/" },
    title:
      "Going Pro and Going Viral: How Aimee Massie Cracked Australia's 'Wild' Skate Scene",
    description:
      "“I would say Australia’s skate culture is a bit more wild. A lot of skaters like to drink and skate and they send it a bit harder.”",
    author: "ARIELLE RICHARDS",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "Going-Pro-and-Going-Viral:",
  },
  {
    id: "fhiwehesh2w484",
    alt: "",
    imgSrc: "/assets/images/couch.webp",
    width: 884,
    height: 496,
    category: { name: "shopping", href: "/" },
    title:
      "The Best Velvet Couches (for Bisexuals, Aesthetes, and Everyone Else)",
    description:
      "TikTok has declared green velvet couches a bisexual fave, but they're sexy, comfortable, and perfect for everyone, negroni-drinker or not.",
    author: 'MARY FRANCES "FRANCKY" KNAPP',
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "The-Best-Velvet-Couches",
  },
  {
    id: "43asfdfyrfjrf6",
    alt: "",
    imgSrc: "/assets/images/spotlight3.webp",
    width: 1422,
    height: 798,
    category: { name: "Life", href: "/" },
    title: "Man, That's a Nice Sheep",
    description: `Australia's most expensive sheep in over 30 years has "exceptional muscle" and "is very deep right through his carcass."`,
    author: "BRAD ESPOSITO",
    articleLink: "/",
    releaseDate: "10.06.22",
    isTrending: true,
    slug: "Man,-That's-a-Nice-Sheep",
  },
  {
    id: "fhiwehzzeshw484",
    alt: "",
    imgSrc: "/assets/images/horoscope.webp",
    width: 884,
    height: 496,
    category: { name: "life", href: "/" },
    title: "Daily Horoscope: October 18, 2022",
    description: "The moon enters Leo and Venus connects with Mars.",
    author: "ANNABEL GAT",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "Daily-Horoscope:-October-18,-2022",
  },
  {
    id: "fhiwehfe54shw484",
    alt: "",
    imgSrc: "/assets/images/terrorist.webp",
    width: 884,
    height: 496,
    category: { name: "World News", href: "/" },
    title: "Haitian Gang Leader Barbecue Has a Plan For Peace",
    description:
      "As tensions in the troubled nation mount, gang leader Jimmy Chérizier wants to put gang members in government.",
    author: "NATHANIEL JANOWITZ",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "Haitian-Gang-Leader-Barbecue-Has-a-Plan-For-Peace",
  },
  {
    id: "fhiw4rtsfhw484",
    alt: "",
    imgSrc: "/assets/images/girl3.webp",
    width: 884,
    height: 496,
    category: { name: "life", href: "/" },
    title:
      "Going Pro and Going Viral: How Aimee Massie Cracked Australia's 'Wild' Skate Scene",
    description:
      "“I would say Australia’s skate culture is a bit more wild. A lot of skaters like to drink and skate and they send it a bit harder.”",
    author: "ARIELLE RICHARDS",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "Going-Pro-and-Going-Viral:",
  },
  {
    id: "fhiwefdsh2w484",
    alt: "",
    imgSrc: "/assets/images/couch.webp",
    width: 884,
    height: 496,
    category: { name: "shopping", href: "/" },
    title:
      "The Best Velvet Couches (for Bisexuals, Aesthetes, and Everyone Else)",
    description:
      "TikTok has declared green velvet couches a bisexual fave, but they're sexy, comfortable, and perfect for everyone, negroni-drinker or not.",
    author: 'MARY FRANCES "FRANCKY" KNAPP',
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "The-Best-Velvet-Couches",
  },
  {
    id: "fhi357wdfsbw484",
    alt: "",
    imgSrc: "/assets/images/girl.webp",
    width: 884,
    height: 496,
    category: { name: "World News", href: "/" },
    title:
      "She Died After Taking MDMA. Her Friends Burned Her Body to Escape Drug Charges.",
    description:
      "How and why 19-year-old Felicia Teo vanished remained a mystery until last week, when a Singaporean court finally heard what happened that night.",
    author: "KOH EWE",
    articleLink: "/",
    releaseDate: "10.06.22",
    slug: "She-Died-After-Taking-MDMA",
  },
  {
    id: "fhw43gcgubaw484",
    alt: "",
    imgSrc: "/assets/images/wc.webp",
    width: 884,
    height: 496,
    category: { name: "Science", href: "/" },
    title: "We Asked an Expert Why Vaping Makes You Want To Poo",
    description:
      "“If you were to stop vaping, or consuming nicotine, you would probably become constipated. Probably, for a couple of days.”",
    author: "JULIE FENWICK",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "We-Asked-an-Expert-Why-Vaping-Makes-You-Want-To-Poo",
  },
  {
    id: "fhiweherjdvfw484",
    alt: "",
    imgSrc: "/assets/images/coffeecup.webp",
    width: 884,
    height: 496,
    category: { name: "events", href: "/" },
    title: "VICE AUSTRALIA GUIDE TO THE WEEKEND",
    description:
      "Here’s what to do this weekend in and around the world (Australia) ✰ OCTOBER WEEK 2 ✰",
    author: "ARIELLE RICHARDS",
    articleLink: "/",
    releaseDate: "10.05.22",
    slug: "what-to-do-this-weekend",
  },
];
